### ISSUE TITLE
Let's do it!

### ISSUE THREAD

**Issue by j3k0** [j3k0/ganomede-analyze-games#1]
Specs are in the README.md

It's pretty urgent (need to be done-done next week).

Ground work include the "Add impersonation" tasks for:
- [ ] coordinator
- [ ] turngames
- [ ] invitations

**Comment by j3k0** [comment]
Hi @elmigranto - A tournament will be run in 2 weeks, we would like this script to be run at the end of each round to analyze the games played. This is the most urgent thing assigned to you so far.

You don't necessarily have to interrupt abruptly what you are doing right now, but please confirm that you can finish this by next week (Thursday). We need to proof-test it on Friday on production servers. So I make sure it's production-validated and delivered the next Monday (giving us the week end to fix unthought of edge cases)...

Thanks!

**Comment by elmigranto** [comment]
Yeah, sure, let's do this! :)

**Comment by elmigranto** [comment]
Should be done with initial version today, hopefully (turns out fetching a lot of interdependent JSON is amounting to a lot of stuff :)
